### PR TITLE
Update PRTG-CrowdStrike.ps1

### PR DESCRIPTION
**Pull request by cipo80**
Hello Janos,

I've write a small PRTG EXE script in January to check if there are hosts duplicates in Falcon, but only count the duplicates.
This is usefull because sometimes after upgrade the endpoints for example from Win10 to Win11, Falcon create duplicates.
For sure I'm not a "script guy" like you, would be nice if you can integrate and adding the hostname duplicate, I try to show with `<text>` tag, but again I'm not good with the script!

My best regards

### CODE REVIEW

**Comment by Jannos-443** [comment]
Hey cipo80,

I just uploaded a new Test Version "https://github.com/Jannos-443/PRTG-CrowdStrike/blob/main/PRTG-CrowdStrikeTest.ps1"
Could you please Test if it´s working like you want it?

I am not able to Test any Crowdstrike Scripts at the moment :(

**Comment by cipo80** [comment]
Hi Jannos,

thank you for the update, unfortunately the duplicates isn't detected, the strange thing is that there isn't an error, simple detect 0.
In my "fork" version is detected correctly.
Check also the errors at the beginning of the script, there are also in your original version, but isn't affected the script excution by PRTG.

**Comment by Jannos-443** [comment]
my fault, please try again with the new version.

Could you send me the prtg logs from the beginning? in a txt file for formatting pls.
Maybe also try to update the module here.

**Comment by cipo80** [comment]
I tried, but PRTG give this error:

`XML: XML Parser mismatch: Wanted </text>, got </prtg> -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)`

**Comment by cipo80** [comment]
Row 199 missing the < on /text>, now it's working!!

2022-07-22_14h17_53

Definitely I'll put your picture on my nightstand : ))

Thank you for all!

**Comment by Jannos-443** [comment]
Haha thank you ;)
Will fix it later and Upload the final version.

If you got other ideas for features or Sensors write me.

I am happy to help you.

**Comment by cipo80** [comment]
Great, have a nice w.end!

**Pull request closed without merging**
